version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./init-postgresdb.sql:/docker-entrypoint-initdb.d/init-postgresdb.sql
      - postgres_data:/var/lib/postgresql/data
    environment:   # Add environment variables here
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    restart: unless-stopped
    
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
    networks:
      - backend-network
    env_file:
      - .env

    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8085:8081"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network

volumes:
  postgres_data:   # Define the volume name here
    driver: local

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
